packages/transition/package.json, packages/transition/src/process.ts
兼容 Web 下 style-unit 对 rpx 的转换设置。
=> fix: 兼容 web 下 style-unit 初始化设置

packages/env/README-zh_CN.md, packages/env/README.md, packages/env/docs-temp/README-zh_CN.md, packages/env/docs-temp/README.md, packages/env/package.json, packages/env/src/index.ts
调整 WeChat env 命名，isWeChatMiniprogram =》isWeChatMiniProgram
=> fix: update isWeChatMiniProgram in env

packages/env/src/index.ts
=> feat: add kraken env judgement

packages/confirm/package.json, packages/confirm/src/index.ts
1. 之前 @balloozzq 更改 package.json 字段没有发版，导致小程序报错
2. 升级 universal-env
=> chore: bump version

packages/env/README-zh_CN.md, packages/env/README.md, packages/env/docs-template/README-zh_CN.md, packages/env/docs-template/README.md, packages/env/package.json, packages/env/src/index.ts, scripts/compile-readme.js
=> feat: support bytedance microapp in universal-env

.eslintrc.js, packages/asyncstorage/.editorconfig, packages/asyncstorage/.eslintignore, packages/asyncstorage/.eslintrc.js, packages/asyncstorage/.gitignore, packages/asyncstorage/.npmignore, packages/asyncstorage/README-zh_CN.md, packages/asyncstorage/README.md, packages/asyncstorage/build.json, packages/asyncstorage/docs-template/README-zh_CN.md, packages/asyncstorage/docs-template/README.md, packages/asyncstorage/package.json, packages/asyncstorage/src/index.ts, packages/asyncstorage/src/quickapp/index.js, packages/asyncstorage/src/weex/index.ts, packages/choose-image/src/weex/index.ts
=> Feat quickapp asyncstorage

packages/transition/package.json, packages/transition/src/web/index.ts
node.style.transition couldn't be set sync with target transition style, so there should settimeout 30ms
=> fix: transition invalid

packages/animation/package.json
=> Fix animation error in TS

packages/alert/README-zh_CN.md, packages/alert/README.md, packages/alert/package.json, packages/alert/src/bytedance-microapp/index.ts, packages/alert/src/types.ts, packages/alert/src/wechat-miniprogram/index.ts, packages/confirm/README-zh_CN.md, packages/toast/README-zh_CN.md, packages/toast/README.md, packages/toast/package.json, packages/toast/src/miniapp/bytedance-microapp/index.ts, packages/toast/src/miniapp/wechat-miniprogram/index.ts, packages/toast/src/types.ts
=> feat(alert): support options used in wechat

packages/device/package.json, packages/device/src/web/index.ts
修正正则test时ua中文案非iphone而是iPhone导致的platform返回数据与文档不符的问题
=> Fix platform

packages/env/package.json
=> chore(env): bump version

packages/choose-image/README-en-US.md, packages/choose-image/README.md, packages/choose-image/docs-template/README-en-US.md, packages/choose-image/docs-template/README.md, packages/choose-image/package.json, packages/choose-image/src/index.ts, packages/choose-image/src/miniapp/ali/index.ts, packages/choose-image/src/miniapp/bytedance-microapp/index.ts, packages/choose-image/src/miniapp/wechat/index.ts, packages/choose-image/src/types.ts, packages/choose-image/src/web/index.ts, packages/choose-image/src/weex/index.ts, packages/file/package.json, packages/file/src/index.ts, packages/file/src/types.ts
* 支持 Web 下传入 accpet
* 支持 Web 下返回原生的 File 对象
* 支持 Web 下禁用 base64 转换，避免大文件时可能会有性能问题
* 补充 ts 声明
* 修正文档（文档上的`base64 | string`是写错了，实际上应该是`string[]`）
=> feat(ChooseImage): Web enhanced

README.en-US.md, README.md, api-config.js, docs/README.en-US.md, docs/packages/interactive/toast/README.en-US.md.c, docs/packages/interactive/toast/README.md.c, docs/packages/interactive/toast/hideToast/README.en-US.md, docs/packages/interactive/toast/hideToast/README.md, docs/packages/interactive/toast/showToast/README.en-US.md, docs/packages/interactive/toast/showToast/README.md, docs/packages/network/request/README.en-US.md, docs/packages/network/request/README.md, docs/packages/quickStart/plugin/README.en-US.md, docs/packages/quickStart/plugin/README.md, scripts/demosSource/demo-package-tpl.js, scripts/docsSource/quickStart/plugin/README.md, src/packages/base/canIUse/docs/README.en-US.md, src/packages/base/canIUse/docs/README.md, src/packages/file/docs/download/README.md, src/packages/network/request/docs/README.en-US.md, src/packages/network/request/docs/README.md
* fix: caniuse utils依赖
* fix: 解锁demo 的rax-app 版本
* docs: 替换 api 字段
* docs: 文档字段更新
Co-authored-by: yitan.lgh <yitan.lgh@alibaba-inc.com>
=> Fix/caniuse (#142)

api-config.js, docs/packages/network/request/README.en-US.md, docs/packages/network/request/README.md, package.json, src/packages/network/request/CHANGELOG.md, src/packages/network/request/demo/index.tsx, src/packages/network/request/docs/README.en-US.md, src/packages/network/request/docs/README.md, src/packages/network/request/src/bytedance-microapp/index.ts, src/packages/network/request/src/common.ts, src/packages/network/request/src/types.ts, src/packages/network/request/src/web/index.ts, src/packages/network/request/src/wechat-miniprogram/index.ts, types/global.d.ts
* feat: request support JSONP method
* fix: fix wx.request params header name error
re #140
Co-authored-by: yitan.lgh <yitan.lgh@alibaba-inc.com>
=> Feature: request API support JSONP method (#144)

api-config.js, scripts/build-plugin/gulp/conf/babel.js, scripts/build-plugin/gulp/gulpfile.js, src/packages/file/CHANGELOG.md, src/packages/file/src/web/upload.ts, src/packages/interactive/alert/CHANGELOG.md, src/packages/interactive/alert/src/common.ts, src/packages/interactive/element/CHANGELOG.md, src/packages/interactive/element/src/web/getBoundingClientRect.ts, src/packages/interactive/element/src/web/getScrollOffset.ts, src/packages/interactive/toast/CHANGELOG.md, src/packages/interactive/toast/src/utils/index.ts, src/packages/network/request/src/common.ts, src/packages/network/request/src/types.ts, src/packages/network/request/src/web/index.ts
Co-authored-by: yitan.lgh <yitan.lgh@alibaba-inc.com>
=> feat: tranform ES6 to ES5 (#146)

package.json, src/packages/interactive/pullDownRefresh/demo/index.tsx, src/packages/interactive/pullDownRefresh/docs/README.en-US.md.c, src/packages/interactive/pullDownRefresh/docs/README.md.c, src/packages/interactive/pullDownRefresh/docs/onPullDownRefresh/README.en-US.md, src/packages/interactive/pullDownRefresh/docs/onPullDownRefresh/README.md, src/packages/interactive/pullDownRefresh/src/common.ts, src/packages/interactive/pullDownRefresh/src/types.ts, src/packages/interactive/pullDownRefresh/src/web/onPullDownRefresh.ts
将pullDownRefresh中的自执行代码删除，
将onPullDownRefresh中增加一个eventCallback参数，为用户在触发下拉刷新时调用的回调函数
=> fix: 修改pullDownRefresh的自执行代码

api-config.js, src/packages/storage/src/ali-miniapp/getStorageSync.ts, src/packages/storage/src/bytedance-microapp/getStorageSync.ts, src/packages/storage/src/common.ts, src/packages/storage/src/index.ts, src/packages/storage/src/types.ts, src/packages/storage/src/web/getStorageSync.ts, src/packages/storage/src/wechat-miniprogram/getStorageSync.ts
=> fix: getStorage res type

scripts/docs/build.js, scripts/docs/buildDocs.js
=> Fix docs/0.6.28

package.json, scripts/build-plugin/gulp/gulpfile.js, scripts/build-plugin/gulp/gulpfileMain.js, src/packages/canvas/src/types.ts, src/packages/device/scan/src/types.ts, src/packages/file/src/types.ts, src/packages/interactive/actionSheet/src/types.ts, src/packages/interactive/alert/src/types.ts, src/packages/interactive/animation/src/types.ts, src/packages/interactive/confirm/src/types.ts, src/packages/interactive/loading/src/types.ts, src/packages/interactive/pullDownRefresh/src/types.ts, src/packages/location/src/types.ts, src/packages/media/image/src/types.ts, src/packages/media/video/src/types.ts, src/packages/navigate/src/types.ts, src/packages/network/request/src/types.ts, src/packages/storage/src/types.ts, types/interface.d.ts
* fix: fix uni/apis types
Co-authored-by: yitan.lgh <yitan.lgh@alibaba-inc.com>
=> fix: 修复大包的types声明缺失的问题 (#190)

api-config.js, package.json, scripts/demo/demosSource/build.json, scripts/demo/demosSource/src/pages/index.tsx, src/packages/interactive/navigationBar/demo/index.tsx, src/packages/interactive/navigationBar/docs/README.en-US.md.c, src/packages/interactive/navigationBar/docs/README.md.c, src/packages/interactive/navigationBar/docs/setNavigationBarColor/README.en-US.md, src/packages/interactive/navigationBar/docs/setNavigationBarColor/README.md, src/packages/interactive/navigationBar/docs/setNavigationBarTitle/README.en-US.md, src/packages/interactive/navigationBar/docs/setNavigationBarTitle/README.md, src/packages/interactive/navigationBar/src/ali-miniapp/index.ts, src/packages/interactive/navigationBar/src/ali-miniapp/setNavigationBarColor.ts, src/packages/interactive/navigationBar/src/ali-miniapp/setNavigationBarTitle.ts, src/packages/interactive/navigationBar/src/bytedance-microapp/index.ts, src/packages/interactive/navigationBar/src/bytedance-microapp/setNavigationBarColor.ts, src/packages/interactive/navigationBar/src/bytedance-microapp/setNavigationBarTitle.ts, src/packages/interactive/navigationBar/src/common.ts, src/packages/interactive/navigationBar/src/index.ts, src/packages/interactive/navigationBar/src/types.ts, src/packages/interactive/navigationBar/src/web/index.ts, src/packages/interactive/navigationBar/src/web/setNavigationBarTitle.ts, src/packages/interactive/navigationBar/src/wechat-miniprogram/index.ts, src/packages/interactive/navigationBar/src/wechat-miniprogram/setNavigationBarColor.ts, src/packages/interactive/navigationBar/src/wechat-miniprogram/setNavigationBarTitle.ts
* feat: api of navigationBar
Co-authored-by: 旺山 <mazhenwen.mzw@alibaba-inc.com>
=> feat: api of setNavigationBar (#199)

api-config.js, package.json, src/packages/interactive/navigationBar/docs/setNavigationBarColor/README.en-US.md, src/packages/interactive/navigationBar/docs/setNavigationBarColor/README.md, src/packages/interactive/navigationBar/docs/setNavigationBarTitle/README.en-US.md, src/packages/interactive/navigationBar/docs/setNavigationBarTitle/README.md, src/packages/interactive/navigationBar/src/types.ts
=> fix: navigationBar  preview link bug

src/packages/media/audio/__test__/__snapshots__/web.test.ts.snap, src/packages/media/audio/__test__/web.test.ts
=> test: add web audio test 

src/packages/media/audio/__test__/__snapshots__/web.test.ts.snap, src/packages/media/audio/__test__/web.test.ts, src/packages/media/audio/src/web/createAudioContext.ts
fix: audio not to be singleton
=> fix: audio not to be singleton

docs/packages/device/makePhoneCall/README.en-US.md, docs/packages/device/makePhoneCall/README.md, docs/packages/interactive/pageScrollTo/README.en-US.md, docs/packages/interactive/pageScrollTo/README.md, docs/packages/navigate/README.en-US.md.c, docs/packages/navigate/README.md.c, docs/packages/navigate/switchTab/README.en-US.md, docs/packages/navigate/switchTab/README.md, src/packages/device/makePhoneCall/docs/README.en-US.md, src/packages/device/makePhoneCall/docs/README.md, src/packages/device/makePhoneCall/src/types.ts, src/packages/device/makePhoneCall/src/web/index.ts, src/packages/interactive/pageScrollTo/docs/README.en-US.md, src/packages/interactive/pageScrollTo/docs/README.md, src/packages/navigate/docs/README.en-US.md.c, src/packages/navigate/docs/README.md.c, src/packages/navigate/docs/switchTab/README.en-US.md, src/packages/navigate/docs/switchTab/README.md
更新 switchTab、pageScrollTo、makePhoneCall 文档
=> chore: 更新 switchTab、pageScrollTo、makePhoneCall 文档

api-config.js, src/packages/location/src/ali-miniapp/getLocation.ts
=> feat: getlocation参数类型修复

api-config.js, src/packages/location/src/ali-miniapp/getLocation.ts
Co-authored-by: 阿进 <chenhongjin.chj@alibaba-inc.com>
=> feat: getlocation参数类型修复 (#260)

api-config.js, src/packages/base/unit-tool/CHANGELOG.md, src/packages/base/unit-tool/src/index.ts
Reverts raxjs/universal-api#263
=> Revert "fix(unit-tool): use windowWidth to replace screenWidth"

api-config.js, src/packages/base/env/CHANGELOG.md, src/packages/base/env/src/index.ts
新增 `isPHA`, `isWindVane`, `isFRM` 三个环境判断
=> feat: add platform in env

src/packages/network/request/src/common.ts
=> bugfix: 修复JSONP解码失败问题

api-config.js
bump  system info 1.0.9
related to #283
=> fix: system info 1.0.9

api-config.js, scripts/build-plugin/source/package-tpl.js
修复 Node 环境下 `Cannot use import statement outside a module` 的报错
=> fix: default exports
